# Generated by Django 3.0.5 on 2021-03-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210310_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='indsLclsCd19',
            new_name='indsLclsCd',
        ),
    ]
