# Generated by Django 3.0.5 on 2021-03-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210310_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indsLclsCd',
        ),
    ]
